apiVersion: v1
data:
  redisHost: {{ include "mychart.redisHost" . }}
kind: ConfigMap
metadata:
  name: zk-redis-config
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}zk-client{{ end }}